"use client"
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ChevronLeft, ChevronRight, Heart } from "lucide-react"

interface EventType { id: string; title: string; description: string | null; duration: number; slug: string }
export function PlayfulLayout({ eventType }: { eventType: EventType }) {
  const [selectedDate, setSelectedDate] = useState<Date | null>(null); const [selectedTime, setSelectedTime] = useState<string | null>(null); const [currentMonth, setCurrentMonth] = useState(new Date()); const [availableSlots, setAvailableSlots] = useState<string[]>([]); const [loadingSlots, setLoadingSlots] = useState(false); const [submitting, setSubmitting] = useState(false); const [confirmed, setConfirmed] = useState(false); const [trackingParams, setTrackingParams] = useState<Record<string, string>>({}); const [formData, setFormData] = useState({ name: "", email: "", phone: "" })

  useEffect(() => { if (typeof window === 'undefined') return; const params = new URLSearchParams(window.location.search); const captured: typeof trackingParams = {}; if (params.get('gclid')) captured.gclid = params.get('gclid')!; setTrackingParams(captured) }, [])
  useEffect(() => { if (!selectedDate) return; const fetchSlots = async () => { setLoadingSlots(true); try { const response = await fetch(`/api/slots?eventTypeId=${eventType.id}&date=${selectedDate.toISOString().split('T')[0]}`); if (response.ok) setAvailableSlots((await response.json()).slots || []) } finally { setLoadingSlots(false) } }; fetchSlots() }, [selectedDate, eventType.id])

  const handleSubmit = async () => { if (!selectedDate || !selectedTime) return; setSubmitting(true); try { const [hours, minutes] = selectedTime.split(':'); const startTime = new Date(selectedDate); startTime.setHours(parseInt(hours), parseInt(minutes), 0); const endTime = new Date(startTime); endTime.setMinutes(endTime.getMinutes() + eventType.duration); const response = await fetch('/api/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventTypeId: eventType.id, startTime: startTime.toISOString(), endTime: endTime.toISOString(), attendeeName: formData.name, attendeeEmail: formData.email, attendeePhone: formData.phone || undefined, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, gclid: trackingParams.gclid }) }); if (response.ok) setConfirmed(true) } finally { setSubmitting(false) } }

  const getDaysInMonth = (date: Date) => { const year = date.getFullYear(), month = date.getMonth(); return { daysInMonth: new Date(year, month + 1, 0).getDate(), startingDayOfWeek: new Date(year, month, 1).getDay() } }
  const { daysInMonth, startingDayOfWeek } = getDaysInMonth(currentMonth); const today = new Date(); today.setHours(0, 0, 0, 0)

  if (confirmed) {
    return <div className="min-h-screen bg-yellow-50 flex items-center justify-center p-4"><div className="bg-white rounded-[3rem] shadow-2xl p-12 max-w-lg w-full text-center border-8 border-yellow-400"><Heart size={64} className="mx-auto mb-6 text-red-500 fill-red-500" /><h2 className="text-5xl font-black text-yellow-600 mb-4">Yippie! 🎉</h2><p className="text-2xl text-gray-700">Du bekommst gleich eine E-Mail!</p></div></div>
  }

  return (
    <div className="min-h-screen bg-yellow-50 py-12 px-4">
      <div className="max-w-4xl mx-auto"><div className="bg-white rounded-[3rem] shadow-2xl p-8 border-8 border-yellow-400"><h1 className="text-6xl font-black text-yellow-600 mb-4">{eventType.title} 🌟</h1>{eventType.description && <p className="text-xl text-gray-700 mb-6">{eventType.description}</p>}<div className="inline-block bg-yellow-400 text-yellow-900 px-8 py-3 rounded-full font-black text-xl">{eventType.duration} Min ⏰</div>

        <div className="grid md:grid-cols-2 gap-8 mt-8"><div><div className="flex items-center justify-between mb-6"><button onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1))} className="p-3 bg-yellow-200 rounded-full hover:bg-yellow-300"><ChevronLeft className="text-yellow-700" /></button><span className="font-black text-2xl text-yellow-700">{currentMonth.toLocaleDateString('de-DE', { month: 'long', year: 'numeric' })}</span><button onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1))} className="p-3 bg-yellow-200 rounded-full hover:bg-yellow-300"><ChevronRight className="text-yellow-700" /></button></div>

            <div className="grid grid-cols-7 gap-2">{['S', 'M', 'D', 'M', 'D', 'F', 'S'].map(d => <div key={d} className="text-center text-sm font-black text-yellow-600 py-2">{d}</div>)}{Array.from({ length: startingDayOfWeek }).map((_, i) => <div key={`e-${i}`} />)}{Array.from({ length: daysInMonth }).map((_, i) => { const day = i + 1; const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day); const isPast = date < today; const isSelected = selectedDate?.getDate() === day && selectedDate?.getMonth() === currentMonth.getMonth(); return <button key={day} onClick={() => !isPast && setSelectedDate(date)} disabled={isPast} className={`aspect-square rounded-2xl font-black text-lg ${isPast ? 'text-gray-300' : isSelected ? 'bg-yellow-400 text-yellow-900 shadow-lg' : 'bg-yellow-100 text-yellow-700 hover:bg-yellow-200'}`}>{day}</button> })}</div></div>

          <div>{selectedDate && (<>{loadingSlots ? <div className="text-center py-8 text-3xl">⏳</div> : availableSlots.length > 0 ? <div className="grid grid-cols-2 gap-3 mb-6">{availableSlots.map(slot => <button key={slot} onClick={() => setSelectedTime(slot)} className={`py-4 rounded-2xl font-black ${selectedTime === slot ? 'bg-yellow-400 text-yellow-900 shadow-lg' : 'bg-yellow-100 text-yellow-700 hover:bg-yellow-200'}`}>{slot}</button>)}</div> : <p className="text-2xl">😢 Keine Zeiten</p>}{selectedTime && <div className="space-y-4"><Input value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} placeholder="Dein Name 👤" className="border-4 border-yellow-300 rounded-2xl text-lg" /><Input type="email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} placeholder="E-Mail 📧" className="border-4 border-yellow-300 rounded-2xl text-lg" /><Input type="tel" value={formData.phone} onChange={(e) => setFormData({ ...formData, phone: e.target.value })} placeholder="Telefon 📱" className="border-4 border-yellow-300 rounded-2xl text-lg" /><Button onClick={handleSubmit} disabled={submitting || !formData.name || !formData.email} className="w-full bg-yellow-400 hover:bg-yellow-500 text-yellow-900 py-6 rounded-2xl font-black text-xl shadow-lg">{submitting ? '⏳ Moment...' : '🎉 Let\'s go!'}</Button></div>}</>)}</div></div></div></div></div>
  )
}
