"use client"
import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ChevronLeft, ChevronRight, Terminal } from "lucide-react"

interface EventType { id: string; title: string; description: string | null; duration: number; slug: string }
export function TechLayout({ eventType }: { eventType: EventType }) {
  const [selectedDate, setSelectedDate] = useState<Date | null>(null); const [selectedTime, setSelectedTime] = useState<string | null>(null); const [currentMonth, setCurrentMonth] = useState(new Date()); const [availableSlots, setAvailableSlots] = useState<string[]>([]); const [loadingSlots, setLoadingSlots] = useState(false); const [submitting, setSubmitting] = useState(false); const [confirmed, setConfirmed] = useState(false); const [trackingParams, setTrackingParams] = useState<Record<string, string>>({}); const [formData, setFormData] = useState({ name: "", email: "", phone: "" })

  useEffect(() => { if (typeof window === 'undefined') return; const params = new URLSearchParams(window.location.search); const captured: typeof trackingParams = {}; if (params.get('gclid')) captured.gclid = params.get('gclid')!; setTrackingParams(captured) }, [])
  useEffect(() => { if (!selectedDate) return; const fetchSlots = async () => { setLoadingSlots(true); try { const response = await fetch(`/api/slots?eventTypeId=${eventType.id}&date=${selectedDate.toISOString().split('T')[0]}`); if (response.ok) setAvailableSlots((await response.json()).slots || []) } finally { setLoadingSlots(false) } }; fetchSlots() }, [selectedDate, eventType.id])

  const handleSubmit = async () => { if (!selectedDate || !selectedTime) return; setSubmitting(true); try { const [hours, minutes] = selectedTime.split(':'); const startTime = new Date(selectedDate); startTime.setHours(parseInt(hours), parseInt(minutes), 0); const endTime = new Date(startTime); endTime.setMinutes(endTime.getMinutes() + eventType.duration); const response = await fetch('/api/bookings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventTypeId: eventType.id, startTime: startTime.toISOString(), endTime: endTime.toISOString(), attendeeName: formData.name, attendeeEmail: formData.email, attendeePhone: formData.phone || undefined, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, gclid: trackingParams.gclid }) }); if (response.ok) setConfirmed(true) } finally { setSubmitting(false) } }

  const getDaysInMonth = (date: Date) => { const year = date.getFullYear(), month = date.getMonth(); return { daysInMonth: new Date(year, month + 1, 0).getDate(), startingDayOfWeek: new Date(year, month, 1).getDay() } }
  const { daysInMonth, startingDayOfWeek } = getDaysInMonth(currentMonth); const today = new Date(); today.setHours(0, 0, 0, 0)

  if (confirmed) {
    return <div className="min-h-screen bg-slate-950 flex items-center justify-center p-4 font-mono"><div className="bg-slate-900 border-2 border-green-500 p-8 max-w-lg w-full"><div className="flex items-center gap-3 mb-6 text-green-400"><Terminal size={32} /><span className="text-2xl font-bold">$ booking.confirm</span></div><div className="bg-slate-800 border border-green-500/50 p-6 text-green-400"><p>{'{'}</p><p className="ml-4">"status": "SUCCESS",</p><p className="ml-4">"date": "{selectedDate?.toISOString().split('T')[0]}",</p><p className="ml-4">"time": "{selectedTime}"</p><p>{'}'}</p></div></div></div>
  }

  return (
    <div className="min-h-screen bg-slate-950 py-12 px-4 font-mono">
      <div className="max-w-5xl mx-auto"><div className="bg-slate-900 border-2 border-green-500 p-8"><div className="flex items-center gap-3 mb-6 text-green-400"><Terminal size={40} /><div><h1 className="text-3xl font-bold">$ {eventType.title.toLowerCase().replace(/\s/g, '_')}</h1>{eventType.description && <p className="text-green-500/70 mt-1">// {eventType.description}</p>}<p className="text-green-500/70">// Duration: {eventType.duration}min</p></div></div>

        <div className="grid md:grid-cols-2 gap-8"><div><div className="flex items-center justify-between mb-6 bg-slate-800 border border-green-500/50 p-3"><button onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() - 1))} className="text-green-400 hover:text-green-300"><ChevronLeft /></button><span className="text-green-400 font-bold">{currentMonth.toLocaleDateString('en-US', { month: 'short', year: 'numeric' }).toUpperCase()}</span><button onClick={() => setCurrentMonth(new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 1))} className="text-green-400 hover:text-green-300"><ChevronRight /></button></div>

            <div className="grid grid-cols-7 gap-1">{['S', 'M', 'T', 'W', 'T', 'F', 'S'].map(d => <div key={d} className="text-center text-xs text-green-500/70 py-1">{d}</div>)}{Array.from({ length: startingDayOfWeek }).map((_, i) => <div key={`e-${i}`} />)}{Array.from({ length: daysInMonth }).map((_, i) => { const day = i + 1; const date = new Date(currentMonth.getFullYear(), currentMonth.getMonth(), day); const isPast = date < today; const isSelected = selectedDate?.getDate() === day && selectedDate?.getMonth() === currentMonth.getMonth(); return <button key={day} onClick={() => !isPast && setSelectedDate(date)} disabled={isPast} className={`aspect-square text-sm font-bold ${isPast ? 'text-slate-700' : isSelected ? 'bg-green-500 text-slate-900' : 'bg-slate-800 text-green-400 hover:bg-slate-700 border border-green-500/30'}`}>{day}</button> })}</div></div>

          <div>{selectedDate && (<>{loadingSlots ? <div className="text-center py-8 text-green-400">Loading...</div> : availableSlots.length > 0 ? <div className="grid grid-cols-3 gap-2 mb-6">{availableSlots.map(slot => <button key={slot} onClick={() => setSelectedTime(slot)} className={`py-3 font-bold ${selectedTime === slot ? 'bg-green-500 text-slate-900' : 'bg-slate-800 text-green-400 hover:bg-slate-700 border border-green-500/30'}`}>{slot}</button>)}</div> : <p className="text-green-500">// No slots available</p>}{selectedTime && <div className="space-y-4"><Input value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} placeholder="Name" className="bg-slate-800 border-green-500/50 text-green-400 font-mono" /><Input type="email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} placeholder="Email" className="bg-slate-800 border-green-500/50 text-green-400 font-mono" /><Input type="tel" value={formData.phone} onChange={(e) => setFormData({ ...formData, phone: e.target.value })} placeholder="Phone" className="bg-slate-800 border-green-500/50 text-green-400 font-mono" /><Button onClick={handleSubmit} disabled={submitting || !formData.name || !formData.email} className="w-full bg-green-500 hover:bg-green-400 text-slate-900 py-6 font-bold font-mono">{submitting ? '> Booking...' : '> Execute Booking'}</Button></div>}</>)}</div></div></div></div></div>
  )
}
